# Generated by Django 4.2.25 on 2025-10-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='theme_color',
            field=models.CharField(default='#4f46e5', help_text='Hex color code for tenant theme', max_length=20),
        ),
    ]
